# Generated by Django 5.0.4 on 2024-05-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0002_doct'),
    ]

    operations = [
        migrations.CreateModel(
            name='dpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('block', models.IntegerField()),
            ],
        ),
    ]
