# Generated by Django 5.0.4 on 2024-05-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0003_dpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='doct1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=2500)),
            ],
        ),
        migrations.DeleteModel(
            name='doct',
        ),
        migrations.DeleteModel(
            name='dpt',
        ),
    ]
